### PR TITLE
Add grouping and edit demo

### PR DESCRIPTION
**Pull request by flora8984461**
Please feel free to check if my editing example is good as a demo? (Or should I separate each of them?)

Thanks!

the material-icon 4.11.4 is gone, only has 4.11.2 now

### CODE REVIEW

**Comment by flora8984461** [comment]
Btw, I am curious what is the current status on  integrate React context via the context branch? If you are already working on it, maybe I look at other issues. Thanks for your review!

**Comment by matthewoestreich** [comment]
>Btw, I am curious what is the current status on integrate React context via the context branch? If you are already working on it, maybe I look at other issues. Thanks for your review!

That's currently a work in progress - feel free to fork the `context` branch if you would like to contribute! Please let me know if you have any questions about the structure, etc..

**Review by matthewoestreich — APPROVED** [review]
Incredible! Someone actually understood what I was doing with the concept of "global variables".  Thank you so much.

**Comment by flora8984461** [comment]
> > Btw, I am curious what is the current status on integrate React context via the context branch? If you are already working on it, maybe I look at other issues. Thanks for your review!
> 
> That's currently a work in progress - feel free to fork the `context` branch if you would like to contribute! Please let me know if you have any questions about the structure, etc..

Thanks for the info. I do have some questions, I've checked the branch, as for now, it only includes one action, seems like it just started moving things into context. 

Do you have any plans for the structure and next steps? Currently, I can see the contextStore, action, reducers and a new useTable().

Is the next step to move the rest functions from data-manager to the same context & actions & reducers? And add functions to useTable()?

What would you suggest for a better start? 

Thanks! 

Oh I found this discussion here https://github.com/material-table-core/core/discussions/190 
maybe I can move on to this discussion?

**Comment by matthewoestreich** [comment]
At high level, data-manager.js is a sort of homegrown global state manager, the goal is to replace it with context. 

I think we may need a context just for the data and columns. When the data changes, we don't need to rerender the toolbar/search/title components. So that's what I was going to test next. 

The current state of the context branch was just to start the initial structure and get feedback on it.

**Comment by flora8984461** [comment]
> At high level, data-manager.js is a sort of homegrown global state manager, the goal is to replace it with context.
> 
> I think we may need a context just for the data and columns. When the data changes, we don't need to rerender the toolbar/search/title components. So that's what I was going to test next.
> 
> The current state of the context branch was just to start the initial structure and get feedback on it.

IC, thanks! I think what I can do is to do the same and try on my local to see how it goes. More like an investigation stage.

**Comment by matthewoestreich** [comment]
Right on. That's perfect. Thank you so much.

**Pull request merged**
